spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
#        通过服务名称访问服务，并开启小写
          enabled: true
          lower-case-service-id: true
      routes:
        - id: blog
          uri: http://www.baidu.com
          predicates:
            - Path=/**

server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug